variables:
  IMAGE: ubuntu:with-hermitcore
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - prepare
  - build
  - test

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} .
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - make
    - du -hs ./target
  image: ${IMAGE}
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
      - ./target/x86_64-eduos/debug/eduos-rs

# Stage: test
##############################################################################
test:
  stage: test
  script:
    - make run
  image: ${IMAGE}
  tags:
    - docker
  dependencies:
    - build
