jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get -qq update
      sudo apt-get install -y curl wget nasm make gcc g++ build-essential
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      export PATH=$PATH:~/.cargo/bin
      cargo install cargo-xbuild
      cargo install --git https://github.com/RWTH-OS/ehyve.git
      rustup component add rust-src
      make
      lscpu
    displayName: 'Test eduOS-rs on Ubuntu 16.04'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      export PATH=$PATH:$HOME/.cargo/bin
      cargo install cargo-xbuild
      cargo install --git https://github.com/RWTH-OS/ehyve.git
      rustup component add rust-src
      make
    displayName: 'Test eduOS-rs on macOS'
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      Invoke-WebRequest -OutFile rustup-init.exe https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
      ./rustup-init.exe -y --default-toolchain nightly | Out-Null
      Remove-Item -Path "rustup-init.exe"
      $env:Path += ";" + $env:UserProfile + "\.cargo\bin"
      cargo install cargo-xbuild
      cargo install --git https://github.com/RWTH-OS/ehyve.git
      rustup component add rust-src
      cargo xbuild --target x86_64-eduos.json
    displayName: 'Test eduOS-rs on Windows'
