name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        rust: [nightly]
        include:
          - os: macOS-latest
            rust: 'nightly'
            components: 'rustfmt, clippy'
            targets: 'x86_64-apple-darwin'
          - os: windows-latest
            rust: 'nightly'
            components: 'rustfmt, clippy'
            targets: 'x86_64-pc-windows-msvc'
          - os: ubuntu-latest
            rust: 'nightly'
            components: 'rustfmt, clippy'
            targets: 'x86_64-unknown-linux-musl'


    steps:
    - uses: hecrj/setup-rust-action@v1.2.3
      with: 
         rust-version: ${{ matrix.rust }}
         components: ${{ matrix.components || '' }}
         targets: ${{ matrix.targets || '' }}
    - uses: actions/checkout@v1
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Build
      run:
         cargo build -Z build-std=core,alloc --no-default-features --target x86_64-eduos.json
